repos:
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    - id: black
      language_version: python3.9
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-toml
    - id: check-added-large-files
    - id: check-case-conflict
    # - id: detect-aws-credentials
    - id: detect-private-key
    - id: no-commit-to-branch
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0  # or master if you're bold
    hooks:
    - id: interrogate
      args: [--quiet, --fail-under=95]


# Include some way to generate requirements.txt through precommit
