title = "Configuration file"

[initial_setup]
completed = true

[backend]
db_file_dir = "./data/"
db_file = "mutual-fund.db"

[logging]
level = "DEBUG"
file_name = "logs/app.log"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
date_format = "%Y-%b-%d %H:%M:%S"
